### PR TITLE
#8732 Enhance KafkaBridge resource with consumer inactivity timeout and HTTP consumer/producer parts enablement

### PR DESCRIPTION
**Pull request by steffen-karlsson**
Enabling ENVs as part of changes in: https://github.com/strimzi/strimzi-kafka-operator/pull/9820 related to changes in improvement: https://github.com/strimzi/strimzi-kafka-operator/issues/8732

### CODE REVIEW

**Comment by ppatierno** [comment]
@steffen-karlsson thanks for the PR. Is it ready for review then? Could you move out of "Draft"? I think there is no that much to add, right?

**Comment by steffen-karlsson** [comment]
Hello @ppatierno there is a few questions and concerns from my side in https://github.com/strimzi/strimzi-kafka-operator/issues/8732 and @scholzj also left some comments here: https://github.com/strimzi/strimzi-kafka-operator/pull/9820 which is related

**Comment by ppatierno** [comment]
@steffen-karlsson any news on this PR now that the corresponding proposal was accepted?

**Comment by steffen-karlsson** [comment]
> @steffen-karlsson any news on this PR now that the corresponding proposal was accepted?

I've had a lot of things lately, expected to modify it next week. Sorry for the delay

**Comment by steffen-karlsson** [comment]
@ppatierno https://github.com/strimzi/strimzi-kafka-operator/pull/9820 and this one is now ready. Apologies for the delay.

**Review by ppatierno — APPROVED** [review]
LGTM

**Review by scholzj — APPROVED** [review]

**Pull request merged**
