### PR TITLE
docs: adds defaults to consumer properties descriptions

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

**Documentation**
Adds defaults to the consumer properties descriptions.

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]

**Review by scholzj — COMMENTED** [review]
This is a generated API docs AFAIK => I don't think you can change it like this.

**Review by ShubhamRwt — APPROVED** [review]

**Comment by ShubhamRwt** [comment]
Changes looks good to me @PaulRMellor . You can make these changes in the `openapi.json` files

**Comment by ppatierno** [comment]
Yeah sorry @scholzj is right. You should change the two openapi specs instead.

**Comment by PaulRMellor** [comment]
I pushed up the JSON changes now. I forgot to do so.

**Pull request merged**
