### PR TITLE
Enable DOCKER_BUILDKIT

### PR DESCRIPTION
**Pull request by krishvoor**
This PR will allow users to seamlessly build containers
on all the architectures without additionally passing build-args.

Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Why not do this via `docker buildx` the same way as it is done in the operators repository?

**Comment by krishvoor** [comment]
Hi Jakub,
Apologies for the delayed response.
> Why not do this via docker buildx the same way as it is done in the operator's repository?

Yes, for any one-off build on non-x86_64 architecture, this approach would work.

Currently, if we follow the instructions and try to build a container image i.e. via `make docker_build` 
the build fails on non-x86_64 architectures, hence these updates.

Please let me know, in case there are other workarounds.

**Comment by scholzj** [comment]
> Currently, if we follow the instructions and try to build a container image i.e. via make docker_build
the build fails on non-x86_64 architectures, hence these updates.

Sorry, I'm not sure I follow. It does not fail for the operators.

**Comment by krishvoor** [comment]
You are right, as you pointed out earlier, operators are handling this via `$DOCKER_BUILDX` in the Makefile
https://github.com/strimzi/strimzi-kafka-operator/blob/main/Makefile.docker#L21 
And this passes.

However, this is failing on strimzi-kafka-bridge, given the lack of it.

**Comment by krishvoor** [comment]
Further to the above-given context, the problem is arising while downloading the architecture-specific tini binary..
If we do not introduce the above changes it results in picking up the wrong architecture-specific tini version.

**Comment by krishvoor** [comment]
Moving the conversation to #521

**Pull request closed without merging**
