### PR TITLE
Bump test container to 0.108.0

### PR DESCRIPTION
**Pull request by see-quick**
This PR updates a recently released version of the test container (i.e., 0.108.0).

### CODE REVIEW

**Comment by ppatierno** [comment]
@see-quick I see stuff keep failing during the build (on Travis CI as well), can you take a look please?

**Comment by ppatierno** [comment]
It seems that it's failing at the same point with this error:

```java
ProducerIT>HttpBridgeITAbstract.cleanUp:165 » Execution org.apache.kafka.common.errors.UnknownTopicOrPartitionException: This server does not host this topic-partition.
```
and only with Java 11 on both Travis CI and Azure pipeline.

**Comment by see-quick** [comment]
Yeah, I will take a look on that tomorrow.

**Comment by ppatierno** [comment]
@see-quick any news on this. I am planning to start RC1 today/tomorrow.

**Comment by see-quick** [comment]
> @see-quick any news on this. I am planning to start RC1 today/tomorrow.



> @see-quick any news on this. I am planning to start RC1 today/tomorrow.

Updated. It seems that the KRaft upgrade caused some disruption (revert back to **ZK-based seems to work fine**). I will do some investigation but I don't want to block the release. Moreover, I created [1].

[1] - https://github.com/strimzi/strimzi-kafka-bridge

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
