### PR TITLE
fixes #103 Removed Spring Boot dependency

### LINKED ISSUE #103: Remove Spring Boot dependency
The Spring Boot dependency is not needed and it adds only complexity. The bridge needs a refactoring for avoiding using Spring Boot.

### PR DESCRIPTION
**Pull request by shubhamvashisht**

### CODE REVIEW

**Comment by ppatierno** [comment]
@shubhamvashisht are you still working on that since December 2018 or I can close this?

**Comment by shubhamvashisht** [comment]
@ppatierno I somehow missed the requested changes. will give it a look.
ps: don't close

**Comment by ppatierno** [comment]
@shubhamvashisht we have planned to work on this one and we start to have strict time. Are you close to give an update or I can just "steal" the issue and work on that?

**Comment by shubhamvashisht** [comment]
@ppatierno. Not close to an update. Please "steal".

**Comment by ppatierno** [comment]
@shubhamvashisht ok, I will work on that. Thanks anyway.

**Pull request closed without merging**
