### PR TITLE
Bump Netty to 4.1.78

### PR DESCRIPTION
**Pull request by scholzj**
Netty 4.1.77 seems to have some vulnerabilities. This PR updates Netty to 4.1.78.

### CODE REVIEW

**Comment by ppatierno** [comment]
@scholzj can you provide more details/links to which vulnerabilities you are referring to please?

**Comment by scholzj** [comment]
@ppatierno https://sbom.lift.sonatype.com/report/T1-a0368c8f29fdaa555824-6d0a62700b0dd7-1657135667-01ed90a5e70343ac841cdc400fde1f45

**Comment by ppatierno** [comment]
I saw it's a CWE not a CVE and cannot find any link where it's fixed in 4.1.78. I see issues opened but not fixes in place. Maybe I just don't see it?

**Comment by scholzj** [comment]
Even a CWE is vulnerability.

**Comment by ppatierno** [comment]
If it's fixed it makes sense but I don't see if it's fixed in 4.1.78 https://netty.io/news/2022/06/14/4-1-78-Final.html
Where did you get the info that it was fixed in 4.1.78? If not fixed, it doesn't make much sense to update imho until the new fixed release.

**Pull request closed without merging**
