### PR TITLE
Make ProducerRecord value nullable

### LINKED ISSUE #462: Allow sending messages with null value
I expect to be able to override a message by sending a null value, but it's not supported by Kafka Bridge.
```
POST /topics/my-topic
{
    "records": [
        {
            "key": "id123",
            "value": null
        }
    ]
}
```

## Expected result:
OK. Status 200

## Received
Validation error. Status 400
```
{
  "error_code": 400,
  "message": "Validation error on: body.records[0].value - $.records[0].value: null found, object expected"
}
```

### PR DESCRIPTION
**Pull request by neemiasjnr**
This PR fixes #462 

This is my first PR on Strimzi project, please let me know if I'm missing something or anything I can improve.

This PR patches some minor details, but for my use case it is very important. I'm running Kafka, Kafka Connect and I'm producing some messages through Kafka Bridge. For GDPR reasons I configured my ElasticSearch connector to delete a document on ElasticSearch if I send a null value (`behavior.on.null.values: "delete"`). At the moment Kafka Bridge doesn't support messages with null values (for more information: https://github.com/strimzi/strimzi-kafka-bridge/issues/462).

**Changes**
- Update openapi specs to allow null values on ProducerRecord spec
- Added a test to check if it's getting status 200 when sending a message with null value
- Minor: add asciidoctor as dependency on HACKING.md

### CODE REVIEW

**Comment by neemiasjnr** [comment]
I'm not sure how I can fix the issue on Travis

**Comment by stanlyDoge** [comment]
Hi, thanks for the PR! I am looking at it.

**Review by stanlyDoge — APPROVED** [review]

**Comment by stanlyDoge** [comment]
Would you like to write a test? :)

**Comment by ppatierno** [comment]
Agree, we would love to have at least one test for it. Thanks!

**Comment by ppatierno** [comment]
@neemiasjnr any news on this? it's possible we are going to do a new release soon, so if you want this one included you should work on it, if you have time.

**Comment by neemiasjnr** [comment]
Hey thanks for the comments, sorry I was travelling and will start working on the test today!

**Comment by neemiasjnr** [comment]
@ppatierno @stanlyDoge I added a test for it, I hope it is in good conditions

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
