### PR TITLE
doc changes for path parameters

### PR DESCRIPTION
**Pull request by MandarJKulkarni**
Signed-off-by: mandarjkulkarni <mjkool@gmail.com>

Fixed path parameter description for

POST /consumers/{groupid}/instances/{name}/subscription

GET /consumers/{groupid}/instances/{name}/subscription

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@ppatierno @MandarJKulkarni I think the document is generated from code and it needs to be changed in some other place as well?

**Comment by MandarJKulkarni** [comment]
> @ppatierno @MandarJKulkarni I think the document is generated from code and it needs to be changed in some other place as well?

Checking now.

**Comment by MandarJKulkarni** [comment]
@scholzj @ppatierno 
Getting below error in builds

```
ERROR: Uncommitted changes in documentation:
M	documentation/book/api/paths.adoc
Run the following to add up-to-date resources:
  make docu_api \
    && git add documentation/book/ \
    && git commit -s -m 'Update generated documentation'
Makefile:67: recipe for target 'docu_check' failed
```

Perhaps adoc files are auto generated and checked in?

**Comment by scholzj** [comment]
@MandarJKulkarni My guess is that you should generate the docs with `make docu_api` and commit it in. The check failing the CI just checks that it is all committed properly.

**Comment by MandarJKulkarni** [comment]
> @MandarJKulkarni My guess is that you should generate the docs with `make docu_api` and commit it in. The check failing the CI just checks that it is all committed properly.

The earlier error with uncommited files was gone after I removed the adoc file from the PR.
Now only openAPI.json is present in the PR.

Below are the test failures with the PR. Not sure why.

```
[ERROR] Errors: 
[ERROR]   AdminClientIT » ExceptionInInitializer
[ERROR]   ConsumerGeneratedNameIT.beforeAll:91 » ContainerLaunch Container startup faile...
[ERROR]   ConsumerIT » NoClassDefFound Could not initialize class io.strimzi.kafka.bridg...
[ERROR]   ConsumerSubscriptionIT » NoClassDefFound Could not initialize class io.strimzi...
[ERROR]   HttpCorsIT.beforeAll:75 » ContainerLaunch Container startup failed
[ERROR]   OtherServicesIT » NoClassDefFound Could not initialize class io.strimzi.kafka....
[ERROR]   ProducerIT » NoClassDefFound Could not initialize class io.strimzi.kafka.bridg...
[ERROR]   SeekIT » NoClassDefFound Could not initialize class io.strimzi.kafka.bridge.ht...

[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Makefile.maven:11: recipe for target 'java_verify' failed
make: *** [java_verify] Error 1
The command "./.travis/build.sh" exited with 2.
```

**Comment by scholzj** [comment]
Ok. I guess that needs some help from @ppatierno or @sknot-rh then.

**Comment by scholzj** [comment]
Hmm, I do not think the CI errors are really related to your PR. They seem to happen for me in other Pr as well.

**Comment by scholzj** [comment]
@MandarJKulkarni I did some fixes to the main branch. Could you try to rebase if it helps?

**Comment by MandarJKulkarni** [comment]
> @MandarJKulkarni I did some fixes to the main branch. Could you try to rebase if it helps?

Merged my branch with master.

**Comment by MandarJKulkarni** [comment]
Finally the build has passed. Thanks @scholzj .
@sknot-rh please have a look.

**Review by scholzj — APPROVED** [review]

**Comment by MandarJKulkarni** [comment]
@scholzj @ppatierno While the PR is merged long ago.

I still don't see the corrections in API documentation HTMLs.
https://strimzi.io/docs/bridge/latest/#_subscribe and https://strimzi.io/docs/bridge/latest/#_listsubscriptions

**Comment by scholzj** [comment]
From the code it looks like the docs are generated from `openapiv2.json` and not from `openapi.json`.

**Pull request merged**
