### PR TITLE
Assertions are simplified.

### PR DESCRIPTION
**Pull request by kamaci**

### CODE REVIEW

**Comment by see-quick** [comment]
Hey, @kamaci thanks for the PR! I am wondering that usage of `org.hamcrest.MatcherAssert.assertThat` would be better. For instance, we are using assertThat everywhere in `strimzi-operator STs` if it is possible. Moreover, you have signoff all commits with the following command:`git commit -s  -m 'assertion simplified'`. Would it be possible to change that to `assertThat` thing? 

example:
```
instead of writing like this
assertEquals(0, this.offsets.get(new TopicPartition("my_topic", 0)).offset());
use this
assertThat(this.offsets.get(new TopicPartition("my_topic", 0)).offset(), is(0));
```

**Comment by kamaci** [comment]
I've updated the PR!

**Comment by see-quick** [comment]
Yes, I see thanks. Also as I mentioned in the previous comment you have to `signoff` all your commits with all the previous one. You can check `DCO` logs. 
```
Commit sha: e985109, Author: kamaci, Committer: kamaci; The sign-off is missing.
Commit sha: 182b888, Author: kamaci, Committer: kamaci; The sign-off is missing.
```

**Comment by kamaci** [comment]
> Yes, I see thanks. Also as I mentioned in the previous comment you have to `signoff` all your commits with all the previous one. You can check `DCO` logs.
> 
> ```
> Commit sha: e985109, Author: kamaci, Committer: kamaci; The sign-off is missing.
> Commit sha: 182b888, Author: kamaci, Committer: kamaci; The sign-off is missing.
> ```

I've rebased last two commits and signed-off them.

**Review by ppatierno — APPROVED** [review]

**Comment by ppatierno** [comment]
@kamaci the tests are failing because I guess you should check the value with the Long literal so using something like `is(0L)` and so on.

**Review by ppatierno — CHANGES_REQUESTED** [review]
@kamaci the tests are failing because I guess you should check the value with the Long literal so using something like is(0L) and so on, can you fix this please?

**Comment by kamaci** [comment]
> @kamaci the tests are failing because I guess you should check the value with the Long literal so using something like is(0L) and so on, can you fix this please?

I've fixed the tests!

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Review by scholzj — APPROVED** [review]

**Review by stanlyDoge — APPROVED** [review]

**Pull request merged**
