### PR TITLE
Dependencies bump

### PR DESCRIPTION
**Pull request by tombentley**
This PR bumps some dependencies. It's a WIP pending the release of a new version of the Strimzi oauth library.

### CODE REVIEW

**Comment by ppatierno** [comment]
@tombentley out of curiosity, why those changes in the doc?

**Comment by tombentley** [comment]
@ppatierno those are due to the bump to swagger2markup version. They are not _strictly_ necessary, so I could revert if you prefer, but they seem to be harmless.

**Comment by ppatierno** [comment]
no need to revert, I was just curious about which change implied the doc change.

**Comment by ppatierno** [comment]
I opened issue #381 for removing this Kafka direct dependency as soon as we have a new Vert.x Kafka client version (3.8.x or 3.9) bringing Kafka 2.4.0 or more.

**Pull request merged**
