### PR TITLE
Extract consumer client.rack from /opt/strimzi/init/rack.id if present

### PR DESCRIPTION
**Pull request by robobario**
Why:
To support rack awareness the strimzi kafka operator will mount in a file containing the rack.id, this can be appended to the consumer configuration if it is present

This has a complementaty PR in strimzi-kafka-operator to mount in the file and populate it via an init container https://github.com/strimzi/strimzi-kafka-operator/pull/7339

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM. Thanks.

**Review by ppatierno — COMMENTED** [review]
We should take into account that the bridge can be used even without the Strimzi operator so on installation where the Kafka cluster is deployed "by hand".
How is it going to work in this case if the user wants rack-awareness? I see this change is just related to the docker container configuration.

**Comment by scholzj** [comment]
@ppatierno When users runs it without the operator, they have to configure the bridge them self. So they can set the `kafka.consumer.client.rack` to whatever they want directly in the config file. This change needs to be done only for the operator where we set it automatically.

**Review by ppatierno — APPROVED** [review]
LGTM

**Pull request merged**
