### PR TITLE
Update hamcrest dependency

### PR DESCRIPTION
**Pull request by stanlyDoge**
Signed-off-by: Stanislav Knot <sknot@redhat.com>

Use version 2.2 instead of very old 1.3

### CODE REVIEW

**Comment by ppatierno** [comment]
@stanlyDoge just genuine question. Any specific reasons for this upgrade?

**Comment by stanlyDoge** [comment]
I was alterted by QE guys the 1.3 is 7 years old so we should use a newer version.

**Comment by ppatierno** [comment]
Let's try to align with the operator first and see if all works there.

**Comment by ppatierno** [comment]
So before approving and merging this one, I would align with the operator as well. You could open a PR for that.

**Comment by Frawless** [comment]
@ppatierno https://github.com/strimzi/strimzi-kafka-operator/pull/2156

**Comment by ppatierno** [comment]
@Frawless ah! it's part of the huge JUnit 5 migration PR :-)

**Pull request merged**
