### PR TITLE
Trying to add retries on s390x tests failing

### PR DESCRIPTION
**Pull request by ppatierno**
Travis CI s390x pipeline only seems to have a lot of flakyness with tests failing.
This PR adds some retries to make it more automatic (instead of me re-run jobs more and more times).

### CODE REVIEW

**Review by Frawless — APPROVED** [review]
Maybe it would be great to put a note there and log an issue?

**Comment by ppatierno** [comment]
> Maybe it would be great to put a note there and log an issue?

I added a comment. Not sure a GitHub issue is really needed. The PR describes what is it for. We don't need to track it imho.

**Comment by ppatierno** [comment]
@Frawless s390x failed as usual but I don't see any retry. Any idea?

**Comment by ppatierno** [comment]
hey @nirmannarang because you were the first one who contributed to s390x in Travis CI, are you able to investigate why tests always keep failing only on this platform and not the others? There is flakyness only on s390x and not on all the other platforms. Thanks!

**Comment by Frawless** [comment]
@ppatierno exactly. Maybe 10 retries is a little bit more than we need, but as long as the tests takes several seconds it's fine from I guess.

 I agree with you, from my POV there is some race in the code that is only visible on s390x.

**Review by Frawless — APPROVED** [review]

**Pull request merged**
