### PR TITLE
move statictests to integration-test phase

### PR DESCRIPTION
**Pull request by elakito**
Signed-off-by: Aki Yoshida <elakito@gmail.com>

Moving StaticTests out of test phase and into integration-test phase.
As a result, mvn clean install will execute all tests except StaticTests and create the package jar and then execute StaticTests.
This should fix https://github.com/strimzi/strimzi-kafka-bridge/issues/388.

### CODE REVIEW

**Comment by ppatierno** [comment]
But in this way, it's never executed on Travis CI and we want it.

**Comment by elakito** [comment]
@ppatierno is the travis test configured at `.travis/build.sh`? This seems to invoke `make java_package` which in turn invokes `mvn package `. In that case, we could instead invoke `mvn verify` to run also the integration-test during the travis test.

If the version info needs to be read from the packaged jar, the test has to wait for the packaging phase.  Or are you thinking of the version info to be read from a resource file (i.e., put release.version under src/main/resources)? In that case, we can read it before the packaging as well.

**Comment by ppatierno** [comment]
@Frawless what do you think about it. I know that @see-quick was thinking about refactoring this test or doing it in a different way.

**Comment by Frawless** [comment]
I am ok with this change. Guess the best option will be to have some test package as we have in operator repo and move all tests which needs jar instead of bridge in memory to there, but we have only one test atm. @see-quick  do you remember which changes you wanted to do?

**Comment by see-quick** [comment]
I lost the idea that I had about the approach we should use but this change seems completely appropriate to me. One thing to consider is that we are going to have two builds in our CI:

1. In-memory Kafka with in-memory Kafka Bridge
2. Standalone Kafka with Standalonee Kafka Bridge

Moreover, on TravisCI we will have to execute `mvn verify` to invoke all tests with Static one?

**Comment by ppatierno** [comment]
> Moreover, on TravisCI we will have to execute mvn verify to invoke all tests with Static one?

@see-quick this is what @elakito was suggesting.
@elakito can you make this change?

**Comment by elakito** [comment]
@ppatierno OK. I'll make the travis change.

**Comment by elakito** [comment]
I have made the change and also verified the travis job successfully executed StaticTests.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Review by Frawless — APPROVED** [review]

**Pull request merged**
